yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('', views.index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/yatube/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/templates/includes/article.html
{% load thumbnail %}
<article>
  <ul>
    {% if author_reference_flag %}
      <li>
        Автор:
        <a href="{% url 'posts:profile' post.author.username %}"> {{ post.author.get_full_name }}<a>
      </li>
    {% endif %}
    <li>
      Дата публикации: {{ post.created|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text|linebreaksbr }}</p>    
  <a href="{% url 'posts:post_detail' post.id %}">подробнее</a>
  <br>
  {% if post.group and group_reference_flag %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{ post.group.title }}</a>
  {% endif %} 
  {% if not forloop.last %}<hr>{% endif %}
</article>

yatube/templates/includes/footer.html
<div class="footer-copyright text-center py-3">© {{ year }} Copyright 
  <p><span style="color:red">Ya</span>tube</p> 
</div>   

yatube/templates/includes/form_field.html
{% load user_filters %}
{% csrf_token %}
{% for field in form %}
  <div class="form-group row my-3"
    {% if field.field.required %} 
      aria-required="true"
    {% else %}
      aria-required="false"
    {% endif %}
  >
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
        {% if field.field.required %}
          <span class="required text-danger">*</span>
        {% endif %}
    </label>
    <div>
    {{ field|addclass:'form-control' }}
      {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
          {{ field.help_text|safe }}
        </small>
      {% endif %}
    </div>
  </div>
{% endfor %}

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %}  
      <li class="nav-item"> 
        <a class="nav-link
        {% if view_name  == 'about:author' %}
        active
        {% endif %}"
        class="nav-link" href="{% url 'about:author' %}">Об авторе</a>
      </li>
      <li class="nav-item">
        <a class="nav-link
        {% if view_name  == 'about:tech' %}
        active
        {% endif %}"
        class="nav-link" href="{% url 'about:tech' %}">Технологии</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item"> 
        <a class="nav-link
        {% if view_name  == 'posts:post_create' %}
        active
        {% endif %}"
        class="nav-link" href="{% url 'posts:post_create' %}">Новая запись</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link
        {% if view_name  == 'users:password_change_form' %}
        active
        {% endif %}"
        class="nav-link link-light" href="{% url 'users:password_change_form' %}">Изменить пароль</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link
        {% if view_name  == 'users:logout' %}
        active
        {% endif %}"
        class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
      </li>
      <li class="nav-item navbar-text">
        <a class="nav-item navbar-text" class="nav-link" href="{% url 'posts:profile' user.username %}">
          Пользователь: {{ user.username }}
        </a>
      </li>
      {% else %}
      <li class="nav-item"> 
        <a class="nav-link
        {% if view_name  == 'users:login' %}
        active
        {% endif %}"
        class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link
        {% if view_name  == 'users:signup' %}
        active
        {% endif %}"
        class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
      </li>
      {% endif %}
      {% endwith %}
    </ul>
  </div>
</nav>      

yatube/templates/includes/input_error.html
{% if form.errors %}
{% for field in form %}
  {% for error in field.errors %}            
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
  <div class="alert alert-danger">
    {{ error|escape }}
  </div>
{% endfor %}
{% endif %}