yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('', views.index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/yatube/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    """Модель группы."""

    title = models.CharField(
        verbose_name='Имя',
        max_length=200,
        help_text='Введите название группы',
    )
    slug = models.SlugField(
        verbose_name='Адрес',
        unique=True,
        help_text='Введите слаг группы',
    )
    description = models.TextField(
        verbose_name='Описание',
        help_text='Введите описание группы',
    )

    class Meta:
        """Метаданные модели группы."""
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'
        ordering = ('title',)

    def __str__(self) -> str:
        """Вернуть название группы."""
        return self.title


class Post(CreatedModel):
    """Модель поста."""

    text = models.TextField(
        verbose_name='Текст',
        help_text='Введите текст поста',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
        related_name='posts',
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True,
    )

    class Meta:
        """Метаданные модели группы."""
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('-created',)

    def __str__(self):
        """Вернуть содержимое поста."""
        return self.text[:settings.NUMBER_OF_CHARACTERS_IN_TEXT_OF_POST]


class Comment(CreatedModel):
    """Модель комментариев."""

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='Комментарий',
        help_text='Прокомментируйте запись',
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Комментатор',
        related_name='comments',
    )
    text = models.TextField(
        verbose_name='Комментарий',
        help_text='Введите комментарий',
    )

    class Meta:
        """Метаданные модели комментария."""
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ('-created',)

    def __str__(self):
        """Вернуть текст комментария."""
        return self.text[:settings.NUMBER_OF_CHARACTERS_IN_TEXT_OF_POST]


class Follow(CreatedModel):
    """Модель подписки на авторов."""

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Подписчик',
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='following',
    )

    class Meta:
        """Метаданные модели комментария."""
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        ordering = ('-created',)
        constraints = [
            models.UniqueConstraint(
                fields=['author', 'user'],
                name='unique_follow'
            )
        ]

yatube/posts/forms.py
from django import forms
from django.conf import settings

from .models import Comment, Post


class PostForm(forms.ModelForm):
    """Форма создания поста."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs['placeholder'] = (
            'Введите сюда свой текст'
        )
        self.fields['group'].empty_label = (
            'Выберите группу, если желаете 🙂'
        )

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Текст поста',
            'group': 'Группа поста'
        }
        help_texts = {
            'text': 'Введите сюда содержимое поста',
            'group': 'Выберите группу, если хотите'
        }

    def clean_text(self):
        post_text = self.cleaned_data['text']
        for word in settings.FORBIDDEN_WORDS:
            if word in post_text.lower():
                raise forms.ValidationError(f'Слово {word} запрещено')
        return post_text


class CommentForm(forms.ModelForm):
    """Форма для комментрия."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs['placeholder'] = (
            'Введите сюда комментарий'
        )

    class Meta:
        model = Comment
        fields = ('text', )
        labels = {
            'text': 'Текст комментария',
        }
        help_texts = {
            'text': 'Введите сюда комментарий',
        }

    def clean_text(self):
        comment_text = self.cleaned_data['text']
        for word in settings.FORBIDDEN_WORDS:
            if word in comment_text.lower():
                raise forms.ValidationError(f'Слово {word} запрещено')
        return comment_text

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post
from .utils import paginator

User = get_user_model()


@cache_page(20, key_prefix='index_page')
def index(request):
    """Получить последние десять из всех записей."""
    post_list = Post.objects.all()
    page_obj = paginator(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Получить последние десять из записей группы."""
    group: Group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = paginator(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """Показать страницу автора"""
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    page_obj = paginator(request, post_list)
    following = (
        request.user.is_authenticated
        and author.following
        .filter(user=request.user)
        .exists()
    )
    context = {
        'page_obj': page_obj,
        'author': author,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """Показать информацию о посте"""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(
        request.POST or None
    )
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """Добавить пост."""
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        temp_form = form.save(commit=False)
        temp_form.author = request.user
        temp_form.save()
        return redirect('posts:profile', temp_form.author)
    context = {'form': form}
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    """Изменить пост."""
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        return redirect('posts:post_detail', post_id=post_id)
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(
            user=request.user,
            author=author
        )
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    request.user.follower.filter(author=author).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
  Редактировать пост
{% else %}
  Новый пост
{% endif %}    
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">       
        {% if is_edit %}
          Редактировать пост
        {% else %}
          Новый пост
        {% endif %}            
        </div>
        <div class="card-body">   
          {% include 'includes/input_error.html' %}     
          <form method="post" enctype="multipart/form-data"
            {% if action_url %}
            action="{% url action_url %}"
            {% endif %}
          >
            {% include 'includes/form_field.html' %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Добавить
              {% else %}
                Сохранить
              {% endif %} 
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  Ваши подписки
{% endblock %}

{% block header %}
  Ваши подписки
{% endblock %}

{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'includes/article.html' with group_reference_flag=True author_reference_flag=True %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
  {{ group.title }}
{% endblock %}

{% block header %}{{ group.title }}{% endblock %}

{% block content %}
  <p> {{ group.description }} </p>
  {% for post in page_obj %}
    {% include 'includes/article.html' with author_reference_flag=True %}
  {% endfor %}

  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block header %}
  Последние обновления на сайте
{% endblock %}

{% load cache %}
{% cache 20 index_page %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'includes/article.html' with group_reference_flag=True author_reference_flag=True %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}
{% endcache %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}

{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.created|date:"d E Y" }}
        </li>
        {% if post.group.slug %}
        <li class="list-group-item">
          Группа:
          <a href="{% url 'posts:group_list' post.group.slug %}">
            {{ post.group.title }}
          </a>
        </li>
        {% endif %}
        <li class="list-group-item">
          Автор:
          <a href="{% url 'posts:profile' post.author %}">
          {{ post.author.get_full_name }}
          </a>
          {{ post.author.username }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
          все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
       <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaksbr }}</p>
      {% if post.author == user %}
      <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
        Редактировать запись
      </a>
      {% endif %} 
      {% include 'posts/includes/comment.html' %}
    </article>
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} 
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}

{% block header %}
  Все посты пользователя {{ author.get_full_name }}
{% endblock %}

{% block content %}
<div class="mb-5">
  <h3>Всего постов: {{ author.posts.count }}</h3>
  {% if author != user %}
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
    {% endif %}
  {% endif %}
  {% for post in page_obj %}
    {% include 'includes/article.html' with group_reference_flag=True %}
{% endfor %}
</div>
{% include 'posts/includes/paginator.html' %}
{% endblock %}